"""empty message

Revision ID: 71643cb41be8
Revises: 855ede25ad1e
Create Date: 2021-06-22 15:00:58.148092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71643cb41be8'
down_revision = '855ede25ad1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_constraint('fk_answer_user_id_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_answer_user_id_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
